package com.github.elebras1.flecs.processor;

import com.palantir.javapoet.*;

import javax.lang.model.element.Modifier;
import javax.lang.model.element.PackageElement;
import javax.lang.model.element.TypeElement;
import javax.lang.model.element.Element;
import java.util.List;
import java.util.function.Supplier;

public class ComponentMapGenerator {

    private static final ClassName COMPONENT_INTERFACE = ClassName.get("com.github.elebras1.flecs", "Component");
    private static final ClassName COMPONENT_VIEW_INTERFACE = ClassName.get("com.github.elebras1.flecs", "ComponentView");
    private static final String MAP_PACKAGE = "com.github.elebras1.flecs";
    private static final String MAP_COMPONENT_CLASS_NAME = "ComponentMap";

    public JavaFile generateComponentMap(List<TypeElement> components) {
        TypeSpec.Builder mapClass = TypeSpec.classBuilder(MAP_COMPONENT_CLASS_NAME)
                .addAnnotation(AnnotationSpec.builder(SuppressWarnings.class).addMember("value", "$S", "unchecked").build())
                .addModifiers(Modifier.PUBLIC, Modifier.FINAL)
                .addField(this.createComponentSizeField(components))
                .addField(this.createComponentsField())
                .addField(this.createComponentViewsField())
                .addField(this.createClassValueField(components))
                .addStaticBlock(this.createStaticInitializer(components))
                .addMethod(this.createConstructor())
                .addMethod(this.createGetIndexMethod())
                .addMethod(this.createSizeMethod())
                .addMethod(this.createGetInstanceMethod())
                .addMethod(this.createGetViewMethod());

        return JavaFile.builder(MAP_PACKAGE, mapClass.build())
                .addFileComment("Generated by ComponentMapGenerator.")
                .indent("    ")
                .build();
    }

    private FieldSpec createComponentSizeField(List<TypeElement> components) {
        return FieldSpec.builder(int.class, "COMPONENT_COUNT",
                Modifier.PRIVATE,
                Modifier.STATIC,
                Modifier.FINAL)
                .initializer("$L", components.size())
                .build();
    }

    private FieldSpec createComponentsField() {
        return FieldSpec.builder(ArrayTypeName.of(ParameterizedTypeName.get(
                        COMPONENT_INTERFACE, WildcardTypeName.subtypeOf(Object.class))),
                "COMPONENTS",
                Modifier.PRIVATE,
                Modifier.STATIC,
                Modifier.FINAL
        ).build();
    }

    private FieldSpec createComponentViewsField() {
        ParameterizedTypeName supplierType = ParameterizedTypeName.get(ClassName.get(Supplier.class), COMPONENT_VIEW_INTERFACE);
        return FieldSpec.builder(
                ArrayTypeName.of(supplierType),
                "VIEWS",
                Modifier.PRIVATE,
                Modifier.STATIC,
                Modifier.FINAL
        ).build();
    }

    private FieldSpec createClassValueField(List<TypeElement> components) {
        ParameterizedTypeName classValueType = ParameterizedTypeName.get(
                ClassName.get(ClassValue.class), ClassName.get(Integer.class));

        TypeSpec anonymousClassValue = TypeSpec.anonymousClassBuilder("")
                .superclass(classValueType)
                .addMethod(MethodSpec.methodBuilder("computeValue")
                        .addAnnotation(Override.class)
                        .addModifiers(Modifier.PROTECTED)
                        .returns(ClassName.get(Integer.class))
                        .addParameter(ParameterizedTypeName.get(ClassName.get(Class.class), WildcardTypeName.subtypeOf(Object.class)), "clazz")
                        .addCode(this.createComputeValueBody(components))
                        .build())
                .build();

        return FieldSpec.builder(classValueType, "COMPONENT_INDEX",
                        Modifier.PRIVATE,
                        Modifier.STATIC,
                        Modifier.FINAL)
                .initializer("$L", anonymousClassValue)
                .build();
    }

    private CodeBlock createComputeValueBody(List<TypeElement> components) {
        CodeBlock.Builder builder = CodeBlock.builder();
        int index = 0;
        for (TypeElement component : components) {
            String packageName = this.getPackageName(component);
            String recordName = component.getSimpleName().toString();
            ClassName recordClass = ClassName.get(packageName, recordName);
            builder.addStatement("if (clazz == $T.class) return $L", recordClass, index++);
        }
        builder.addStatement("return -1");
        return builder.build();
    }

    private CodeBlock createStaticInitializer(List<TypeElement> components) {
        CodeBlock.Builder builder = CodeBlock.builder();

        builder.add("COMPONENTS = new $T[] {\n", ParameterizedTypeName.get(COMPONENT_INTERFACE, WildcardTypeName.subtypeOf(Object.class)));
        for (TypeElement component : components) {
            String packageName = this.getPackageName(component);
            String recordName = component.getSimpleName().toString();
            ClassName componentClass = ClassName.get(packageName, recordName + "Component");
            builder.add("    $T.getInstance(),\n", componentClass);
        }
        builder.add("};\n\n");

        builder.add("VIEWS = new $T[] {\n", ClassName.get(Supplier.class));
        for (TypeElement component : components) {
            String packageName = this.getPackageName(component);
            String recordName = component.getSimpleName().toString();
            ClassName viewClass = ClassName.get(packageName, recordName + "View");
            builder.add("    $T::new,\n", viewClass);
        }
        builder.add("};\n");

        return builder.build();
    }

    private MethodSpec createConstructor() {
        return MethodSpec.constructorBuilder()
                .addModifiers(Modifier.PRIVATE)
                .build();
    }

    private MethodSpec createGetIndexMethod() {
        return MethodSpec.methodBuilder("getIndex")
                .addModifiers(Modifier.PUBLIC, Modifier.STATIC)
                .addParameter(ParameterizedTypeName.get(ClassName.get(Class.class), WildcardTypeName.subtypeOf(Object.class)), "componentClass")
                .returns(TypeName.INT)
                .addStatement("return COMPONENT_INDEX.get(componentClass)")
                .build();
    }

    private MethodSpec createSizeMethod() {
        return MethodSpec.methodBuilder("size")
                .addModifiers(Modifier.PUBLIC, Modifier.STATIC)
                .returns(TypeName.INT)
                .addStatement("return COMPONENT_COUNT")
                .build();
    }

    private MethodSpec createGetInstanceMethod() {
        return MethodSpec.methodBuilder("getInstance")
                .addModifiers(Modifier.PUBLIC, Modifier.STATIC)
                .addTypeVariable(TypeVariableName.get("T"))
                .addParameter(ParameterizedTypeName.get(ClassName.get(Class.class), TypeVariableName.get("T")), "componentClass")
                .returns(ParameterizedTypeName.get(COMPONENT_INTERFACE, TypeVariableName.get("T")))
                .addStatement("int index = COMPONENT_INDEX.get(componentClass)")
                .addStatement("return index >= 0 ? ($T<T>) COMPONENTS[index] : null", COMPONENT_INTERFACE)
                .build();
    }

    private MethodSpec createGetViewMethod() {
        ParameterizedTypeName supplierType = ParameterizedTypeName.get(ClassName.get(Supplier.class), COMPONENT_VIEW_INTERFACE);

        return MethodSpec.methodBuilder("getView")
                .addModifiers(Modifier.PUBLIC, Modifier.STATIC)
                .addTypeVariable(TypeVariableName.get("T"))
                .addParameter(ParameterizedTypeName.get(ClassName.get(Class.class), TypeVariableName.get("T")), "componentClass")
                .returns(COMPONENT_VIEW_INTERFACE)
                .addStatement("int index = COMPONENT_INDEX.get(componentClass)")
                .addStatement("$T supplier = index >= 0 ? VIEWS[index] : null", supplierType)
                .addStatement("return supplier != null ? supplier.get() : null")
                .build();
    }

    private String getPackageName(TypeElement element) {
        Element current = element.getEnclosingElement();
        while (current != null && !(current instanceof PackageElement)) {
            current = current.getEnclosingElement();
        }
        return current != null ? ((PackageElement) current).getQualifiedName().toString() : "";
    }
}