package com.github.elebras1.flecs.processor;

import com.palantir.javapoet.*;

import javax.lang.model.element.Modifier;
import javax.lang.model.element.TypeElement;
import javax.lang.model.element.VariableElement;
import java.lang.foreign.MemorySegment;
import java.util.ArrayList;
import java.util.List;

public class ComponentRowViewGenerator extends AbstractGenerator {

    private static final String COMPONENT_ROW_VIEW_INTERFACE = "com.github.elebras1.flecs.ComponentRowView";

    @Override
    public JavaFile generate(TypeElement recordElement, List<VariableElement> fields)  {
        String packageName = this.getPackageName(recordElement);
        String recordName = recordElement.getSimpleName().toString();
        String componentRowViewClassName = recordName + "RowView";

        String componentReference = packageName + "." + recordName + "Component";

        TypeSpec componentClass = TypeSpec.classBuilder(componentRowViewClassName)
                .addModifiers(Modifier.PUBLIC, Modifier.FINAL)
                .addSuperinterface(ClassName.bestGuess(COMPONENT_ROW_VIEW_INTERFACE))
                .addField(FieldSpec.builder(MemorySegment.class, "segment", Modifier.PRIVATE).build())
                .addField(FieldSpec.builder(int.class, "count", Modifier.PRIVATE).build())
                .addField(FieldSpec.builder(int.class, "size", Modifier.PRIVATE).build())
                .addMethods(this.createSetters())
                .addMethods(this.createGetters(fields, componentReference))
                .build();

        return JavaFile.builder(packageName, componentClass)
                .addFileComment("Generated by ComponentRowViewGenerator")
                .indent("    ")
                .build();
    }

    private List<MethodSpec> createSetters() {
        MethodSpec setSegment = MethodSpec.methodBuilder("setSegment")
                .addAnnotation(Override.class)
                .addModifiers(Modifier.PUBLIC)
                .addParameter(MemorySegment.class, "segment")
                .addJavadoc("Internal API - Do not use.\n")
                .addStatement("this.segment = segment")
                .build();

        MethodSpec setCount = MethodSpec.methodBuilder("setCount")
                .addAnnotation(Override.class)
                .addModifiers(Modifier.PUBLIC)
                .addParameter(int.class, "count")
                .addJavadoc("Internal API - Do not use.\n")
                .addStatement("this.count = count")
                .build();

        return List.of(setSegment, setCount);
    }

    private List<MethodSpec> createGetters(List<VariableElement> fields, String componentReference) {
        List<MethodSpec> methods = new ArrayList<>();

        MethodSpec segmentMethod = MethodSpec.methodBuilder("segment")
                .addAnnotation(Override.class)
                .addModifiers(Modifier.PUBLIC)
                .returns(MemorySegment.class)
                .addStatement("return this.segment")
                .build();
        methods.add(segmentMethod);

        MethodSpec countMethod = MethodSpec.methodBuilder("count")
                .addAnnotation(Override.class)
                .addModifiers(Modifier.PUBLIC)
                .returns(int.class)
                .addStatement("return this.count")
                .build();
        methods.add(countMethod);

        MethodSpec sizeMethod = MethodSpec.methodBuilder("size")
                .addAnnotation(Override.class)
                .addModifiers(Modifier.PUBLIC)
                .returns(long.class)
                .addStatement("return $L.LAYOUT.byteSize()", componentReference)
                .build();
        methods.add(sizeMethod);

        for(VariableElement field : fields) {
            methods.addAll(this.createGetters(field, componentReference));
        }

        return methods;
    }

    private List<MethodSpec> createGetters(VariableElement field, String componentReference) {
        String fieldName = field.getSimpleName().toString();
        String offsetName = "OFFSET_" + fieldName.toUpperCase();
        String getterName = fieldName + "Offset";

        MethodSpec offsetMethod = MethodSpec.methodBuilder(getterName)
                .addModifiers(Modifier.PUBLIC)
                .returns(long.class)
                .addStatement("return $L.$L", componentReference, offsetName)
                .build();

        long byteSize = this.byteSize(field);
        MethodSpec sizeMethod = MethodSpec.methodBuilder(fieldName + "Size")
                .addModifiers(Modifier.PUBLIC)
                .returns(long.class)
                .addStatement("return $LL", byteSize)
                .build();

        return List.of(offsetMethod, sizeMethod);
    }

    private long byteSize(VariableElement field) {
        return switch (field.asType().toString()) {
            case "byte", "boolean" -> 1L;
            case "short", "char" -> 2L;
            case "int", "float" -> 4L;
            case "long", "double" -> 8L;
            case "java.lang.String" -> this.getStringSize(field);
            case "byte[]", "boolean[]" -> (long) this.getArrayLength(field);
            case "short[]", "char[]" -> 2L * this.getArrayLength(field);
            case "int[]", "float[]" -> 4L * this.getArrayLength(field);
            case "long[]", "double[]" -> 8L * this.getArrayLength(field);
            default -> -1L;
        };
    }
}
