package com.github.elebras1.flecs.processor;

import com.github.elebras1.flecs.util.internal.codegen.CodeBuilder;
import com.github.elebras1.flecs.util.internal.codegen.SourceFile;

import javax.lang.model.element.TypeElement;
import javax.lang.model.element.VariableElement;
import java.util.List;

public class ComponentRowViewGenerator extends AbstractGenerator {

    private static final String COMPONENT_ROW_VIEW_INTERFACE = "com.github.elebras1.flecs.ComponentRowView";

    @Override
    public SourceFile generate(TypeElement recordElement, List<VariableElement> fields) {
        String packageName = this.getPackageName(recordElement);
        String recordName = recordElement.getSimpleName().toString();
        String componentRowViewClassName = recordName + "RowView";
        String componentReference = packageName + "." + recordName + "Component";

        CodeBuilder body = new CodeBuilder();
        body.append("public final class ").append(componentRowViewClassName).append(" implements ComponentRowView {").newline();

        body.indent4().append("private MemorySegment segment;").newline();
        body.indent4().append("private int count;").newline();
        body.indent4().append("private int size;").newline();

        body.newline();
        body.indent4().append("/**").newline();
        body.indent4().append(" * Internal API - Do not use.").newline();
        body.indent4().append(" */").newline();
        body.indent4().append("@Override").newline();
        body.indent4().append("public void setSegment(MemorySegment segment) {").newline();
        body.indent8().append("this.segment = segment;").newline();
        body.indent4().append("}").newline();

        body.newline();
        body.indent4().append("/**").newline();
        body.indent4().append(" * Internal API - Do not use.").newline();
        body.indent4().append(" */").newline();
        body.indent4().append("@Override").newline();
        body.indent4().append("public void setCount(int count) {").newline();
        body.indent8().append("this.count = count;").newline();
        body.indent4().append("}").newline();

        body.newline();
        body.indent4().append("@Override").newline();
        body.indent4().append("public MemorySegment segment() {").newline();
        body.indent8().append("return this.segment;").newline();
        body.indent4().append("}").newline();

        body.newline();
        body.indent4().append("@Override").newline();
        body.indent4().append("public int count() {").newline();
        body.indent8().append("return this.count;").newline();
        body.indent4().append("}").newline();

        body.newline();
        body.indent4().append("@Override").newline();
        body.indent4().append("public long size() {").newline();
        body.indent8().append("return ").append(componentReference).append(".LAYOUT.byteSize();").newline();
        body.indent4().append("}").newline();

        for (VariableElement field : fields) {
            String fieldName = field.getSimpleName().toString();
            String offsetName = "OFFSET_" + fieldName.toUpperCase();
            long byteSize = this.byteSize(field);

            body.newline();
            body.indent4().append("public long ").append(fieldName).append("Offset() {").newline();
            body.indent8().append("return ").append(componentReference).append(".").append(offsetName).append(";").newline();
            body.indent4().append("}").newline();

            body.newline();
            body.indent4().append("public long ").append(fieldName).append("Size() {").newline();
            body.indent8().append("return ").append(byteSize).append("L;").newline();
            body.indent4().append("}").newline();
        }

        body.append("}").newline();

        return SourceFile.builder(packageName, componentRowViewClassName)
                .fileComment("Generated by ComponentRowViewGenerator")
                .addImport(COMPONENT_ROW_VIEW_INTERFACE)
                .addImport("java.lang.foreign.MemorySegment")
                .classBody(body.toString())
                .build();
    }

    private long byteSize(VariableElement field) {
        return switch (field.asType().toString()) {
            case "byte", "boolean" -> 1L;
            case "short", "char" -> 2L;
            case "int", "float" -> 4L;
            case "long", "double" -> 8L;
            case "java.lang.String" -> this.getStringSize(field);
            case "byte[]", "boolean[]" -> (long) this.getArrayLength(field);
            case "short[]", "char[]" -> 2L * this.getArrayLength(field);
            case "int[]", "float[]" -> 4L * this.getArrayLength(field);
            case "long[]", "double[]" -> 8L * this.getArrayLength(field);
            default -> -1L;
        };
    }
}