package com.github.elebras1.flecs.processor;
import com.github.elebras1.flecs.util.internal.codegen.CodeBuilder;
import com.github.elebras1.flecs.util.internal.codegen.SourceFile;

import javax.lang.model.element.TypeElement;
import javax.lang.model.element.VariableElement;
import java.util.List;

public class ComponentGenerator extends AbstractGenerator {

    protected static final String MEMORY_ACCESS_CLASS = "com.github.elebras1.flecs.util.internal.MemoryAccess";
    protected static final String COMPONENT_INTERFACE = "com.github.elebras1.flecs.Component";
    protected static final int DEFAULT_STRING_SIZE = 32;

    @Override
    public SourceFile generate(TypeElement recordElement, List<VariableElement> fields) {
        String packageName = this.getPackageName(recordElement);
        String recordName = recordElement.getSimpleName().toString();
        String componentClassName = recordName + "Component";

        CodeBuilder body = new CodeBuilder();
        body.append("public final class ").append(componentClassName)
                .append(" implements Component<").append(recordName).append("> {").newline();

        body.append(buildLayoutField(recordName, fields));

        for (VariableElement field : fields) {
            body.append(buildOffsetField(field));
        }

        body.newline();
        body.indent4().append("private static final class Holder {").newline();
        body.indent8().append("static final ").append(componentClassName).append(" INSTANCE = new ").append(componentClassName).append("();").newline();
        body.indent4().append("}").newline();

        body.newline();
        body.indent4().append("public ").append(componentClassName).append("() {").newline();
        body.indent4().append("}").newline();

        body.newline();
        body.indent4().append("@Override").newline();
        body.indent4().append("public MemoryLayout layout() {").newline();
        body.indent8().append("return LAYOUT;").newline();
        body.indent4().append("}").newline();

        body.newline();
        body.append(buildWriteMethod(recordName, fields));

        body.newline();
        body.append(buildReadMethod(recordName, fields));

        body.newline();
        body.indent4().append("@Override").newline();
        body.indent4().append("public ").append(recordName).append("[] createArray(int size) {").newline();
        body.indent8().append("return new ").append(recordName).append("[size];").newline();
        body.indent4().append("}").newline();

        body.newline();
        body.indent4().append("public static ").append(componentClassName).append(" create() {").newline();
        body.indent8().append("return new ").append(componentClassName).append("();").newline();
        body.indent4().append("}").newline();

        body.newline();
        body.indent4().append("public static ").append(componentClassName).append(" getInstance() {").newline();
        body.indent8().append("return Holder.INSTANCE;").newline();
        body.indent4().append("}").newline();

        body.append("}").newline();

        return SourceFile.builder(packageName, componentClassName)
                .fileComment("Generated by ComponentProcessor")
                .addImport("com.github.elebras1.flecs.Component")
                .addImport("com.github.elebras1.flecs.util.internal.MemoryAccess")
                .addImport("java.lang.foreign.MemoryLayout")
                .addImport("java.lang.foreign.MemorySegment")
                .classBody(body.toString())
                .build();
    }

    private String buildLayoutField(String recordName, List<VariableElement> fields) {
        CodeBuilder sb = new CodeBuilder();
        sb.indent4().append("protected static final MemoryLayout LAYOUT = MemoryAccess.createStructLayout(\"").append(recordName).append("\"");

        if (!fields.isEmpty()) {
            sb.append(",").newline();
            for (int i = 0; i < fields.size(); i++) {
                VariableElement field = fields.get(i);
                String fieldName = field.getSimpleName().toString();
                String type = field.asType().toString();
                String layoutMethod = this.getLayoutMethod(type);

                sb.indent8().append("MemoryAccess.");
                if ("java.lang.String".equals(type)) {
                    sb.append(layoutMethod).append("(").append(this.getStringSize(field)).append(")");
                } else if (type.endsWith("[]")) {
                    sb.append(layoutMethod).append("(").append(this.getArrayLength(field)).append(")");
                } else {
                    sb.append(layoutMethod).append("()");
                }
                sb.append(".withName(\"").append(fieldName).append("\")");
                if (i < fields.size() - 1) {
                    sb.append(",").newline();
                }
            }
        }
        sb.append(");").newline();
        return sb.toString();
    }

    private String buildOffsetField(VariableElement field) {
        String fieldName = field.getSimpleName().toString();
        String constantName = "OFFSET_" + fieldName.toUpperCase();
        return new CodeBuilder()
                .indent4().append("protected static final long ").append(constantName)
                .append(" = MemoryAccess.offsetOf(LAYOUT, \"").append(fieldName).append("\");").newline()
                .toString();
    }

    private String buildWriteMethod(String recordName, List<VariableElement> fields) {
        CodeBuilder sb = new CodeBuilder();
        sb.indent4().append("@Override").newline();
        sb.indent4().append("public void write(MemorySegment segment, long offset, ").append(recordName).append(" data) {").newline();
        for (VariableElement field : fields) {
            String fieldName = field.getSimpleName().toString();
            String offsetName = "OFFSET_" + fieldName.toUpperCase();
            String typeName = field.asType().toString();
            sb.indent8().append("MemoryAccess.set(segment, offset + ").append(offsetName)
                    .append(", data.").append(fieldName).append("()");
            if ("java.lang.String".equals(typeName)) {
                sb.append(", ").append(this.getStringSize(field));
            } else if (typeName.endsWith("[]")) {
                sb.append(", ").append(this.getArrayLength(field));
            }
            sb.append(");").newline();
        }
        sb.indent4().append("}").newline();
        return sb.toString();
    }

    private String buildReadMethod(String recordName, List<VariableElement> fields) {
        CodeBuilder sb = new CodeBuilder();
        sb.indent4().append("@Override").newline();
        sb.indent4().append("public ").append(recordName).append(" read(MemorySegment segment, long offset) {").newline();
        for (VariableElement field : fields) {
            String fieldName = field.getSimpleName().toString();
            String offsetName = "OFFSET_" + fieldName.toUpperCase();
            String typeName = field.asType().toString();
            String getter = this.getGetterMethod(typeName);
            String javaType = "java.lang.String".equals(typeName) ? "String" : typeName;

            sb.indent8().append(javaType).append(" ").append(fieldName)
                    .append(" = MemoryAccess.").append(getter).append("(segment, offset + ").append(offsetName);
            if ("java.lang.String".equals(typeName)) {
                sb.append(", ").append(this.getStringSize(field));
            } else if (typeName.endsWith("[]")) {
                sb.append(", ").append(this.getArrayLength(field));
            }
            sb.append(");").newline();
        }
        sb.indent8().append("return new ").append(recordName).append("(");
        for (int i = 0; i < fields.size(); i++) {
            sb.append(fields.get(i).getSimpleName().toString());
            if (i < fields.size() - 1) sb.append(", ");
        }
        sb.append(");").newline();
        sb.indent4().append("}").newline();
        return sb.toString();
    }

    private String getLayoutMethod(String type) {
        return switch (type) {
            case "byte" -> "byteLayout";
            case "short" -> "shortLayout";
            case "int" -> "intLayout";
            case "long" -> "longLayout";
            case "float" -> "floatLayout";
            case "double" -> "doubleLayout";
            case "boolean" -> "booleanLayout";
            case "byte[]" -> "byteArrayLayout";
            case "short[]" -> "shortArrayLayout";
            case "int[]" -> "intArrayLayout";
            case "long[]" -> "longArrayLayout";
            case "float[]" -> "floatArrayLayout";
            case "double[]" -> "doubleArrayLayout";
            case "boolean[]" -> "booleanArrayLayout";
            case "java.lang.String" -> "stringLayout";
            default -> throw new IllegalArgumentException("Unsupported type: " + type);
        };
    }
}