package io.github.elebras1.flecs;

import io.github.elebras1.flecs.util.internal.codegen.CodeBuilder;
import io.github.elebras1.flecs.util.internal.codegen.SourceFile;

import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.ArrayList;
import java.util.List;

public class EntityBaseGenerator extends AbstractBaseGenerator {

    public static void main(String[] args) {
        Path outputDir = args.length > 0 ? Paths.get(args[0]) : Paths.get("src/main/generated");
        EntityBaseGenerator generator = new EntityBaseGenerator();
        int count = generator.generateAndWrite(outputDir);
        System.out.println("Generated " + count + " files in " + outputDir.toAbsolutePath());
    }

    @Override
    public List<SourceFile> generate() {
        List<SourceFile> files = new ArrayList<>();
        files.add(generateEntityBase());
        return files;
    }

    private SourceFile generateEntityBase() {
        CodeBuilder body = new CodeBuilder();

        body.append("public abstract class EntityBase<T extends EntityBase<T>> extends ")
                .append(simpleName(ID_FQN)).append(" {").newline();
        body.newline();
        appendLine(body, 1, "protected EntityBase(" + simpleName(WORLD_FQN) + " world, long id) {");
        appendStatement(body, 2, "super(world, id)");
        appendLine(body, 1, "}");
        body.newline();

        for (int n = 1; n <= MAX_COMPONENTS; n++) {
            appendInsertMethod(body, n);
            body.newline();
        }

        body.append("}").newline();

        return SourceFile.builder(GENERATED_PACKAGE, "EntityBase")
                .fileComment("Generated by EntityBaseGenerator.")
                .addImport(MEMORY_SEGMENT_FQN)
                .addImport(ARENA_FQN)
                .classBody(body.toString())
                .build();
    }

    private void appendInsertMethod(CodeBuilder body, int n) {
        List<String> viewVars = viewTypeVars(n);

        appendLine(body, 1, "@SuppressWarnings(\"unchecked\")");
        List<String> bounds = new ArrayList<>();
        for (String v : viewVars) {
            bounds.add(v + " extends " + simpleName(COMPONENT_VIEW_FQN));
        }

        List<String> typeParams = new ArrayList<>();
        for (String b : bounds) {
            typeParams.add(b);
        }
        String callbackType = callbackInterfaceName(n, ViewMode.COMPONENT_VIEW, EntityMode.WITHOUT_ENTITY);
        String callbackArg = callbackType + "<" + join(viewVars) + ">";

        List<String> params = new ArrayList<>();
        for (int i = 0; i < n; i++) {
            params.add("Class<?> componentClass" + letter(i));
        }
        params.add(callbackArg + " callback");

        StringBuilder signature = new StringBuilder();
        signature.append("public <").append(join(typeParams)).append("> T insert(");
        signature.append(join(params)).append(") {");
        appendLine(body, 1, signature.toString());

        for (int i = 0; i < n; i++) {
            String comp = letter(i);
            appendStatement(body, 2, "long componentId" + comp
                    + " = this.world.componentRegistry().getComponentId(componentClass" + comp + ")");
        }
        body.newline();

        if (n == 1) {
            appendStatement(body, 2, "long sizeA = this.world.componentRegistry().getComponent(componentClassA).size()");
            appendStatement(body, 2, "long addressA = " + simpleName(FLECS_H_FQN)
                    + ".ecs_ensure_id(this.world.worldSeg(), this.id, componentIdA, sizeA).address()");
            appendStatement(body, 2, "VA componentViewA = (VA) this.world.viewCache().getComponentView(componentClassA)");
            appendStatement(body, 2, "componentViewA.setBaseAddress(addressA)");
            appendStatement(body, 2, "callback.accept(componentViewA)");
            appendStatement(body, 2, simpleName(FLECS_H_FQN) + ".ecs_modified_id(this.world.worldSeg(), this.id, componentIdA)");
            appendStatement(body, 2, "return (T) this");
            appendLine(body, 1, "}");
            return;
        }

        appendLine(body, 2, "if (!" + simpleName(FLECS_H_FQN) + ".ecs_is_deferred(this.world.worldSeg())) {");
        appendLine(body, 3, "MemorySegment recordSeg = " + simpleName(FLECS_H_FQN) + ".ecs_record_find(this.world.worldSeg(), this.id);");
        appendLine(body, 3, "if (recordSeg.address() != 0) {");
        appendLine(body, 4, "recordSeg = recordSeg.reinterpret(" + simpleName(ECS_RECORD_T_FQN) + ".layout().byteSize());");
        appendLine(body, 4, "MemorySegment tableSeg = " + simpleName(ECS_RECORD_T_FQN) + ".table(recordSeg);");
        appendLine(body, 4, "if (tableSeg.address() != 0) {");
        appendLine(body, 5, "try (Arena arena = Arena.ofConfined()) {");
        appendLine(body, 6, "MemorySegment diffSeg = " + simpleName(ECS_TABLE_DIFF_T_FQN) + ".allocate(arena);");
        appendLine(body, 6, "MemorySegment idSlot = arena.allocate(" + simpleName(FLECS_H_FQN) + ".C_LONG);");
        appendLine(body, 6, "MemorySegment addedBuf = arena.allocate(" + simpleName(FLECS_H_FQN) + ".C_LONG, " + n + ");");
        appendLine(body, 6, "MemorySegment nextSeg;");
        appendStatement(body, 6, "int addedCount = 0");
        body.newline();

        for (int i = 0; i < n; i++) {
            String comp = letter(i);
            appendStatement(body, 6, "idSlot.set(" + simpleName(FLECS_H_FQN) + ".C_LONG, 0, componentId" + comp + ")");
            appendStatement(body, 6, "nextSeg = " + simpleName(FLECS_H_FQN)
                    + ".flecs_table_traverse_add(this.world.worldSeg(), tableSeg, idSlot, diffSeg)");
            appendStatement(body, 6, "long id" + comp + " = idSlot.get(" + simpleName(FLECS_H_FQN) + ".C_LONG, 0)");
            appendLine(body, 6, "if (nextSeg.address() != tableSeg.address()) {");
            appendStatement(body, 7, "addedBuf.setAtIndex(" + simpleName(FLECS_H_FQN) + ".C_LONG, addedCount++, id" + comp + ")");
            appendLine(body, 6, "} else if ((" + simpleName(ECS_TABLE_DIFF_T_FQN) + ".added_flags(diffSeg) & "
                    + simpleName(FLECS_H_FQN) + ".EcsTableHasDontFragment()) != 0) {");
            appendStatement(body, 7, simpleName(FLECS_H_FQN) + ".ecs_add_id(this.world.worldSeg(), this.id, id" + comp + ")");
            appendStatement(body, 7, "addedBuf.setAtIndex(" + simpleName(FLECS_H_FQN) + ".C_LONG, addedCount++, id" + comp + ")");
            appendLine(body, 6, "}");
            appendStatement(body, 6, "tableSeg = nextSeg");
        }
        body.newline();

        appendLine(body, 6, "if (addedCount > 0) {");
        appendLine(body, 7, "MemorySegment typeSeg = " + simpleName(ECS_TYPE_T_FQN) + ".allocate(arena);");
        appendStatement(body, 7, simpleName(ECS_TYPE_T_FQN) + ".array(typeSeg, addedBuf)");
        appendStatement(body, 7, simpleName(ECS_TYPE_T_FQN) + ".count(typeSeg, addedCount)");
        appendStatement(body, 7, simpleName(FLECS_H_FQN)
                + ".ecs_commit(this.world.worldSeg(), this.id, recordSeg, tableSeg, typeSeg, MemorySegment.NULL)");
        appendLine(body, 6, "}");
        body.newline();

        for (int i = 0; i < n; i++) {
            String comp = letter(i);
            appendStatement(body, 6, "int column" + comp + " = " + simpleName(FLECS_H_FQN)
                    + ".ecs_table_get_column_index(this.world.worldSeg(), tableSeg, componentId" + comp + ")");
            appendStatement(body, 6, "long address" + comp);
            appendLine(body, 6, "if (column" + comp + " == -1) {");
            appendStatement(body, 7, "address" + comp + " = " + simpleName(FLECS_H_FQN)
                    + ".ecs_get_mut_id(this.world.worldSeg(), this.id, componentId" + comp + ")");
            appendLine(body, 6, "} else {");
            appendStatement(body, 7, "address" + comp + " = " + simpleName(FLECS_H_FQN)
                    + ".ecs_record_get_by_column(recordSeg, column" + comp + ", 0L).address()");
            appendLine(body, 6, "}");
        }
        body.newline();

        appendStatement(body, 6, simpleName(FLECS_H_FQN) + ".ecs_table_lock(this.world.worldSeg(), tableSeg)");
        appendLine(body, 6, "try {");
        String[] paramNames = new String[n];
        for (int i = 0; i < n; i++) {
            String comp = letter(i);
            String view = "V" + comp;
            appendStatement(body, 7, view + " componentView" + comp + " = (" + view
                    + ") this.world.viewCache().getComponentView(componentClass" + comp + ")");
            appendStatement(body, 7, "componentView" + comp + ".setBaseAddress(address" + comp + ")");
            paramNames[i] = "componentView" + comp + "";
        }
        appendStatement(body, 7, "callback.accept(" + String.join(", ", paramNames) + ")");
        appendLine(body, 6, "} finally {");
        appendStatement(body, 7, simpleName(FLECS_H_FQN) + ".ecs_table_unlock(this.world.worldSeg(), tableSeg)");
        appendLine(body, 6, "}");
        for (int i = 0; i < n; i++) {
            String comp = letter(i);
            appendStatement(body, 6, simpleName(FLECS_H_FQN)
                    + ".ecs_modified_id(this.world.worldSeg(), this.id, componentId" + comp + ")");
        }
        appendStatement(body, 6, "return (T) this");
        appendLine(body, 5, "}");
        appendLine(body, 4, "}");
        appendLine(body, 3, "}");
        appendLine(body, 2, "}");
        body.newline();

        for (int i = 0; i < n; i++) {
            appendStatement(body, 2, "long address" + letter(i));
        }
        appendLine(body, 2, "if (" + simpleName(FLECS_H_FQN) + ".ecs_is_deferred(this.world.worldSeg())) {");
        for (int i = 0; i < n; i++) {
            String comp = letter(i);
            appendStatement(body, 3, "long size" + comp
                    + " = this.world.componentRegistry().getComponent(componentClass" + comp + ").size()");
            appendStatement(body, 3, "address" + comp + " = " + simpleName(FLECS_H_FQN)
                    + ".ecs_ensure_id(this.world.worldSeg(), this.id, componentId" + comp
                    + ", size" + comp + ").address()");
        }
        appendLine(body, 2, "} else {");
        for (int i = 0; i < n; i++) {
            String comp = letter(i);
            appendStatement(body, 3, "long size" + comp
                    + " = this.world.componentRegistry().getComponent(componentClass" + comp + ").size()");
            appendStatement(body, 3, simpleName(FLECS_H_FQN) + ".ecs_ensure_id(this.world.worldSeg(), this.id, componentId"
                    + comp + ", size" + comp + ")");
        }
        for (int i = 0; i < n; i++) {
            String comp = letter(i);
            appendStatement(body, 3, "address" + comp + " = " + simpleName(FLECS_H_FQN)
                    + ".ecs_get_mut_id(this.world.worldSeg(), this.id, componentId" + comp + ")");
        }
        appendLine(body, 2, "}");
        body.newline();

        String[] fallbackParamNames = new String[n];
        for (int i = 0; i < n; i++) {
            String comp = letter(i);
            String view = "V" + comp;
            appendStatement(body, 2, view + " componentView" + comp + " = (" + view
                    + ") this.world.viewCache().getComponentView(componentClass" + comp + ")");
            appendStatement(body, 2, "componentView" + comp + ".setBaseAddress(address" + comp + ")");
            fallbackParamNames[i] = "componentView" + comp + "";
        }
        appendStatement(body, 2, "callback.accept(" + String.join(", ", fallbackParamNames) + ")");
        for (int i = 0; i < n; i++) {
            String comp = letter(i);
            appendStatement(body, 2, simpleName(FLECS_H_FQN)
                    + ".ecs_modified_id(this.world.worldSeg(), this.id, componentId" + comp + ")");
        }
        appendStatement(body, 2, "return (T) this");

        appendLine(body, 1, "}");
    }
}
