package io.github.elebras1.flecs;

import io.github.elebras1.flecs.internal.codegen.CodeBuilder;
import io.github.elebras1.flecs.internal.codegen.SourceFile;

import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.ArrayList;
import java.util.List;

public class IterationBaseGenerator extends AbstractBaseGenerator {

    private static final String ECS_ITER_T_FQN = "io.github.elebras1.flecs.ecs_iter_t";
    private static final String ECS_ITER_ACTION_T_FQN = "io.github.elebras1.flecs.ecs_iter_action_t";
    private static final String ECS_SYSTEM_DESC_T_FQN = "io.github.elebras1.flecs.ecs_system_desc_t";
    private static final String ECS_OBSERVER_DESC_T_FQN = "io.github.elebras1.flecs.ecs_observer_desc_t";
    private static final String FLECS_SYSTEM_FQN = "io.github.elebras1.flecs.FlecsSystem";
    private static final String FLECS_OBSERVER_FQN = "io.github.elebras1.flecs.Observer";

    private enum BuilderKind {
        SYSTEM(FLECS_SYSTEM_FQN, ECS_SYSTEM_DESC_T_FQN),
        OBSERVER(FLECS_OBSERVER_FQN, ECS_OBSERVER_DESC_T_FQN);

        final String returnTypeFqn;
        final String descTypeFqn;
        final String returnType;
        final String descType;

        BuilderKind(String returnTypeFqn, String descTypeFqn) {
            this.returnTypeFqn = returnTypeFqn;
            this.descTypeFqn = descTypeFqn;
            this.returnType = simpleName(returnTypeFqn);
            this.descType = simpleName(descTypeFqn);
        }
    }

    public static void main(String[] args) {
        Path outputDir = args.length > 0 ? Paths.get(args[0]) : Paths.get("src/main/generated");
        IterationBaseGenerator generator = new IterationBaseGenerator();
        int count = generator.generateAndWrite(outputDir);
        System.out.println("Generated " + count + " files in " + outputDir.toAbsolutePath());
    }

    @Override
    public List<SourceFile> generate() {
        List<SourceFile> files = new ArrayList<>();
        files.add(generateQueryBase());
        files.add(generateBuilderBase("SystemBuilderBase", BuilderKind.SYSTEM));
        files.add(generateBuilderBase("ObserverBuilderBase", BuilderKind.OBSERVER));
        return files;
    }

    private SourceFile generateQueryBase() {
        CodeBuilder body = new CodeBuilder();
        body.append("public abstract class QueryBase {").newline();
        appendLine(body, 1, "protected final " + simpleName(WORLD_FQN) + " world;");
        appendLine(body, 1, "protected final " + simpleName(MEMORY_SEGMENT_FQN) + " querySeg;");
        body.newline();
        appendLine(body, 1, "protected QueryBase(" + simpleName(WORLD_FQN) + " world, " + simpleName(MEMORY_SEGMENT_FQN) + " querySeg) {");
        appendStatement(body, 2, "this.world = world");
        appendStatement(body, 2, "this.querySeg = querySeg");
        appendLine(body, 1, "}");
        body.newline();
        appendLine(body, 1, "protected abstract void checkDestroyed();");

        for (int n = 1; n <= MAX_COMPONENTS; n++) {
            for (ViewMode vm : ViewMode.values()) {
                for (EntityMode em : EntityMode.values()) {
                    body.newline();
                    appendQueryEachMethod(body, n, vm, em);
                }
                body.newline();
                appendQueryFindMethod(body, n, vm);
            }
        }

        body.newline();
        appendQueryEachIterMethod(body);

        body.append("}").newline();

        return SourceFile.builder(GENERATED_PACKAGE, "QueryBase")
                .fileComment("Generated by IterationBaseGenerator.")
                .addImport(WORLD_FQN)
                .addImport(MEMORY_SEGMENT_FQN)
                .addImport(ARENA_FQN)
                .addImport(COMPONENT_FQN)
                .addImport(COMPONENT_VIEW_FQN)
                .addImport(FLECS_H_FQN)
                .addImport(ECS_ITER_T_FQN)
                .addImport(VALUE_LAYOUT_FQN)
                .classBody(body.toString())
                .build();
    }

    private void appendQueryEachMethod(CodeBuilder body, int n, ViewMode vm, EntityMode em) {
        appendEachMethodSignature(body, n, vm, em, "void", "each");
        appendStatement(body, 2, "this.checkDestroyed()");
        appendLine(body, 2, "try (" + simpleName(ARENA_FQN) + " tmpArena = " + simpleName(ARENA_FQN) + ".ofConfined()) {");
        appendStatement(body, 3, simpleName(MEMORY_SEGMENT_FQN) + " iterSeg = " + simpleName(FLECS_H_FQN)
                + ".ecs_query_iter(tmpArena, this.world.worldSeg(), this.querySeg)");
        appendLine(body, 3, "if (iterSeg.address() == 0) {");
        appendStatement(body, 4, "throw new IllegalStateException(\"ecs_query_iter returned a null iterator\")");
        appendLine(body, 3, "}");

        emitComponentLookups(body, 3, n, vm);

        if (vm == ViewMode.COMPONENT_VIEW) {
            appendStatement(body, 3, "this.world.viewCache().resetCursors()");
        }
        if (em == EntityMode.WITH_ITER) {
            appendStatement(body, 3, "Iter iter = new Iter(iterSeg, this.world)");
        }

        appendLine(body, 3, "while (" + simpleName(FLECS_H_FQN) + ".ecs_iter_next(iterSeg)) {");
        if (em == EntityMode.WITH_ENTITY) {
            appendStatement(body, 4, simpleName(MEMORY_SEGMENT_FQN) + " entities = " + simpleName(ECS_ITER_T_FQN) + ".entities(iterSeg)");
        }
        emitFieldOrBase(body, 4, n, vm, "iterSeg");
        appendStatement(body, 4, "int count = " + simpleName(ECS_ITER_T_FQN) + ".count(iterSeg)");
        emitEmptyTableGuard(body, 4, em, "iterSeg");
        emitSelfFlags(body, 4, n, "iterSeg");
        appendLine(body, 4, "for (int i = 0; i < count; i++) {");
        if (em == EntityMode.WITH_ENTITY) {
            appendStatement(body, 5, "long entityId = entities.getAtIndex(" + simpleName(VALUE_LAYOUT_FQN) + ".JAVA_LONG, i)");
        }
        emitInstanceOrView(body, 5, n, vm);
        emitCallbackAccept(body, 5, n, vm, em);
        appendLine(body, 4, "}");
        appendLine(body, 3, "}");
        appendLine(body, 2, "}");
        appendLine(body, 1, "}");
    }

    private void appendQueryFindMethod(CodeBuilder body, int n, ViewMode vm) {
        appendFindMethodSignature(body, n, vm);
        appendStatement(body, 2, "this.checkDestroyed()");
        appendLine(body, 2, "try (" + simpleName(ARENA_FQN) + " tmpArena = " + simpleName(ARENA_FQN) + ".ofConfined()) {");
        appendStatement(body, 3, simpleName(MEMORY_SEGMENT_FQN) + " iterSeg = " + simpleName(FLECS_H_FQN)
                + ".ecs_query_iter(tmpArena, this.world.worldSeg(), this.querySeg)");
        appendLine(body, 3, "if (iterSeg.address() == 0) {");
        appendStatement(body, 4, "throw new IllegalStateException(\"ecs_query_iter returned a null iterator\")");
        appendLine(body, 3, "}");

        emitComponentLookups(body, 3, n, vm);

        if (vm == ViewMode.COMPONENT_VIEW) {
            appendStatement(body, 3, "this.world.viewCache().resetCursors()");
        }

        appendLine(body, 3, "while (" + simpleName(FLECS_H_FQN) + ".ecs_iter_next(iterSeg)) {");
        appendStatement(body, 4, simpleName(MEMORY_SEGMENT_FQN) + " entities = " + simpleName(ECS_ITER_T_FQN) + ".entities(iterSeg)");
        emitFieldOrBase(body, 4, n, vm, "iterSeg");
        appendStatement(body, 4, "int count = " + simpleName(ECS_ITER_T_FQN) + ".count(iterSeg)");
        emitSelfFlags(body, 4, n, "iterSeg");
        appendLine(body, 4, "for (int i = 0; i < count; i++) {");
        emitInstanceOrView(body, 5, n, vm);

        String args = buildArgs(vm == ViewMode.COMPONENT_VIEW ? "componentView" : "componentInstance", n);
        appendLine(body, 5, "if (predicate.test(" + args + ")) {");
        appendStatement(body, 6, "return entities.getAtIndex(" + simpleName(VALUE_LAYOUT_FQN) + ".JAVA_LONG, i)");
        appendLine(body, 5, "}");

        appendLine(body, 4, "}");
        appendLine(body, 3, "}");
        appendLine(body, 2, "}");
        appendStatement(body, 2, "return 0L");
        appendLine(body, 1, "}");
    }

    private SourceFile generateBuilderBase(String className, BuilderKind kind) {
        CodeBuilder body = new CodeBuilder();
        body.append("public abstract class ").append(className).append(" {").newline();
        appendLine(body, 1, "protected final " + simpleName(WORLD_FQN) + " world;");
        appendLine(body, 1, "protected final " + simpleName(MEMORY_SEGMENT_FQN) + " desc;");
        body.newline();
        appendLine(body, 1, "protected " + className + "(" + simpleName(WORLD_FQN) + " world, " + simpleName(MEMORY_SEGMENT_FQN) + " desc) {");
        appendStatement(body, 2, "this.world = world");
        appendStatement(body, 2, "this.desc = desc");
        appendLine(body, 1, "}");
        body.newline();
        appendLine(body, 1, "protected abstract " + kind.returnType + " build();");

        appendBuilderIterFor(body, kind);

        for (int n = 1; n <= MAX_COMPONENTS; n++) {
            for (ViewMode vm : ViewMode.values()) {
                for (EntityMode em : EntityMode.values()) {
                    body.newline();
                    appendBuilderEachMethod(body, n, vm, em, kind);
                }
            }
        }

        body.newline();
        appendBuilderEachIterMethod(body, kind);

        body.append("}").newline();

        return SourceFile.builder(GENERATED_PACKAGE, className)
                .fileComment("Generated by IterationBaseGenerator.")
                .addImport(WORLD_FQN)
                .addImport(MEMORY_SEGMENT_FQN)
                .addImport(COMPONENT_FQN)
                .addImport(COMPONENT_VIEW_FQN)
                .addImport(FLECS_H_FQN)
                .addImport(ECS_ITER_T_FQN)
                .addImport(ECS_ITER_ACTION_T_FQN)
                .addImport(VALUE_LAYOUT_FQN)
                .addImport(kind.returnTypeFqn)
                .addImport(kind.descTypeFqn)
                .classBody(body.toString())
                .build();
    }

    private void appendBuilderIterFor(CodeBuilder body, BuilderKind kind) {
        appendLine(body, 1, "protected abstract Iter iterFor(" + simpleName(MEMORY_SEGMENT_FQN) + " iterSegment);");
        body.newline();
    }

    private void appendBuilderEachMethod(CodeBuilder body, int n, ViewMode vm, EntityMode em, BuilderKind kind) {
        appendEachMethodSignature(body, n, vm, em, kind.returnType, "each");
        emitComponentLookups(body, 2, n, vm);

        appendLine(body, 2, simpleName(MEMORY_SEGMENT_FQN) + " callbackStub = " + simpleName(ECS_ITER_ACTION_T_FQN)
                + ".allocate(iterSegment -> {");
        if (vm == ViewMode.COMPONENT_VIEW) {
            appendStatement(body, 3, "this.world.viewCache().resetCursors()");
        }
        if (em == EntityMode.WITH_ITER) {
            appendStatement(body, 3, "Iter iter = this.iterFor(iterSegment)");
        }
        if (em == EntityMode.WITH_ENTITY) {
            appendStatement(body, 3, simpleName(MEMORY_SEGMENT_FQN) + " entities = " + simpleName(ECS_ITER_T_FQN) + ".entities(iterSegment)");
        }
        emitFieldOrBase(body, 3, n, vm, "iterSegment");
        appendStatement(body, 3, "int count = " + simpleName(ECS_ITER_T_FQN) + ".count(iterSegment)");
        emitEmptyTableGuard(body, 3, em, "iterSegment");
        emitSelfFlags(body, 3, n, "iterSegment");
        appendLine(body, 3, "for (int i = 0; i < count; i++) {");
        if (em == EntityMode.WITH_ENTITY) {
            appendStatement(body, 4, "long entityId = entities.getAtIndex(" + simpleName(VALUE_LAYOUT_FQN) + ".JAVA_LONG, i)");
        }
        emitInstanceOrView(body, 4, n, vm);
        emitCallbackAccept(body, 4, n, vm, em);
        appendLine(body, 3, "}");
        appendLine(body, 2, "}, this.world.arena());");

        appendStatement(body, 2, kind.descType + ".callback(this.desc, callbackStub)");
        appendStatement(body, 2, "return build()");
        appendLine(body, 1, "}");
    }

    private void appendQueryEachIterMethod(CodeBuilder body) {
        appendLine(body, 1, "public void each(IterWithIndexCallback callback) {");
        appendStatement(body, 2, "this.checkDestroyed()");
        appendLine(body, 2, "try (" + simpleName(ARENA_FQN) + " tmpArena = " + simpleName(ARENA_FQN) + ".ofConfined()) {");
        appendStatement(body, 3, simpleName(MEMORY_SEGMENT_FQN) + " iterSeg = " + simpleName(FLECS_H_FQN)
                + ".ecs_query_iter(tmpArena, this.world.worldSeg(), this.querySeg)");
        appendLine(body, 3, "if (iterSeg.address() == 0) {");
        appendStatement(body, 4, "throw new IllegalStateException(\"ecs_query_iter returned a null iterator\")");
        appendLine(body, 3, "}");
        appendStatement(body, 3, "Iter iter = new Iter(iterSeg, this.world)");
        appendLine(body, 3, "while (" + simpleName(FLECS_H_FQN) + ".ecs_iter_next(iterSeg)) {");
        appendStatement(body, 4, "int count = " + simpleName(ECS_ITER_T_FQN) + ".count(iterSeg)");
        appendLine(body, 4, "for (int i = 0; i < count; i++) {");
        appendStatement(body, 5, "callback.accept(iter, i)");
        appendLine(body, 4, "}");
        appendLine(body, 3, "}");
        appendLine(body, 2, "}");
        appendLine(body, 1, "}");
    }

    private void appendBuilderEachIterMethod(CodeBuilder body, BuilderKind kind) {
        appendLine(body, 1, "public " + kind.returnType + " each(IterWithIndexCallback callback) {");
        appendLine(body, 2, simpleName(MEMORY_SEGMENT_FQN) + " callbackStub = " + simpleName(ECS_ITER_ACTION_T_FQN)
                + ".allocate(iterSegment -> {");
        appendStatement(body, 3, "Iter iter = this.iterFor(iterSegment)");
        appendStatement(body, 3, "int count = " + simpleName(ECS_ITER_T_FQN) + ".count(iterSegment)");
        appendLine(body, 3, "for (int i = 0; i < count; i++) {");
        appendStatement(body, 4, "callback.accept(iter, i)");
        appendLine(body, 3, "}");
        appendLine(body, 2, "}, this.world.arena());");
        appendStatement(body, 2, kind.descType + ".callback(this.desc, callbackStub)");
        appendStatement(body, 2, "return build()");
        appendLine(body, 1, "}");
    }

    private void appendEachMethodSignature(CodeBuilder body, int n, ViewMode vm, EntityMode em, String returnType, String methodBase) {
        if (vm == ViewMode.COMPONENT_VIEW) {
            appendLine(body, 1, "@SuppressWarnings(\"unchecked\")");
        }

        List<String> compVars = compTypeVars(n);
        List<String> viewVars = viewTypeVars(n);
        List<String> typeDecls = new ArrayList<>(compVars);
        if (vm == ViewMode.COMPONENT_VIEW) {
            for (String v : viewVars) {
                typeDecls.add(v + " extends " + simpleName(COMPONENT_VIEW_FQN));
            }
        }

        String methodName = vm == ViewMode.COMPONENT_VIEW ? methodBase + "View" : methodBase;
        StringBuilder signature = new StringBuilder();
        signature.append("public ");
        if (!typeDecls.isEmpty()) {
            signature.append("<").append(join(typeDecls)).append("> ");
        }
        signature.append(returnType).append(" ").append(methodName).append("(");

        List<String> params = new ArrayList<>();
        for (String compVar : compVars) {
            params.add("Class<" + compVar + "> componentClass" + compVar);
        }

        String callbackName = callbackInterfaceName(n, vm, em);
        List<String> callbackArgs = vm == ViewMode.COMPONENT_VIEW ? viewVars : compVars;
        String callbackType = callbackName + "<" + join(callbackArgs) + ">";
        params.add(callbackType + " callback");

        signature.append(join(params)).append(") {");
        appendLine(body, 1, signature.toString());
    }

    private void appendFindMethodSignature(CodeBuilder body, int n, ViewMode vm) {
        if (vm == ViewMode.COMPONENT_VIEW) {
            appendLine(body, 1, "@SuppressWarnings(\"unchecked\")");
        }

        List<String> compVars = compTypeVars(n);
        List<String> viewVars = viewTypeVars(n);
        List<String> typeDecls = new ArrayList<>(compVars);
        if (vm == ViewMode.COMPONENT_VIEW) {
            for (String v : viewVars) {
                typeDecls.add(v + " extends " + simpleName(COMPONENT_VIEW_FQN));
            }
        }

        String methodName = vm == ViewMode.COMPONENT_VIEW ? "findView" : "find";
        StringBuilder signature = new StringBuilder();
        signature.append("public ");
        if (!typeDecls.isEmpty()) {
            signature.append("<").append(join(typeDecls)).append("> ");
        }
        signature.append("long ").append(methodName).append("(");

        List<String> params = new ArrayList<>();
        for (String compVar : compVars) {
            params.add("Class<" + compVar + "> componentClass" + compVar);
        }

        String predicateName = predicateInterfaceName(n, vm);
        List<String> predicateArgs = vm == ViewMode.COMPONENT_VIEW ? viewVars : compVars;
        String predicateType = predicateName + "<" + join(predicateArgs) + ">";
        params.add(predicateType + " predicate");

        signature.append(join(params)).append(") {");
        appendLine(body, 1, signature.toString());
    }

    private void emitComponentLookups(CodeBuilder body, int level, int n, ViewMode vm) {
        for (int i = 0; i < n; i++) {
            String comp = letter(i);
            if (vm == ViewMode.COMPONENT_VIEW) {
                appendStatement(body, level, simpleName(COMPONENT_FQN) + "<?> component" + comp
                        + " = this.world.componentRegistry().getComponent(componentClass" + comp + ")");
            } else {
                appendStatement(body, level, simpleName(COMPONENT_FQN) + "<" + comp + "> component" + comp
                        + " = this.world.componentRegistry().getComponent(componentClass" + comp + ")");
            }
        }
        if (vm == ViewMode.COMPONENT_VIEW) {
            for (int i = 0; i < n; i++) {
                String comp = letter(i);
                String view = "V" + comp;
                appendStatement(body, level, view + " componentView" + comp + " = (" + view
                        + ") this.world.viewCache().getComponentView(componentClass" + comp + ")");
            }
        }
        for (int i = 0; i < n; i++) {
            String comp = letter(i);
            appendStatement(body, level, "long size" + comp + " = component" + comp + ".size()");
        }
    }

    private void emitFieldOrBase(CodeBuilder body, int level, int n, ViewMode vm, String iterVar) {
        for (int i = 0; i < n; i++) {
            String comp = letter(i);
            if (vm == ViewMode.COMPONENT_VIEW) {
                appendStatement(body, level, "long base" + comp + " = " + simpleName(FLECS_H_FQN)
                        + ".ecs_field_w_size(" + iterVar + ", size" + comp + ", (byte) " + i + ").address()");
            } else {
                appendStatement(body, level, simpleName(MEMORY_SEGMENT_FQN) + " field" + comp + " = "
                        + simpleName(FLECS_H_FQN) + ".ecs_field_w_size(" + iterVar + ", size" + comp + ", (byte) " + i + ")");
            }
        }
    }

    private void emitEmptyTableGuard(CodeBuilder body, int level, EntityMode em, String iterVar) {
        if (em != EntityMode.WITHOUT_ENTITY) {
            return;
        }
        String condition = "count == 0 && " + simpleName(ECS_ITER_T_FQN) + ".table(" + iterVar + ").address() == 0";
        appendLine(body, level, "if (" + condition + ") {");
        appendLine(body, level + 1, "count = 1;");
        appendLine(body, level, "}");
    }

    private void emitSelfFlags(CodeBuilder body, int level, int n, String iterVar) {
        for (int i = 0; i < n; i++) {
            String comp = letter(i);
            appendStatement(body, level, "boolean isSelf" + comp + " = " + simpleName(FLECS_H_FQN) + ".ecs_field_is_self(" + iterVar + ", (byte) " + i + ")");
        }
    }

    private void emitInstanceOrView(CodeBuilder body, int level, int n, ViewMode vm) {
        for (int i = 0; i < n; i++) {
            String comp = letter(i);
            if (vm == ViewMode.COMPONENT_VIEW) {
                appendStatement(body, level, "componentView" + comp + ".setBaseAddress(base" + comp + " + (long) (isSelf" + comp + " ? i : 0) * size" + comp + ")");
            } else {
                appendStatement(body, level, comp + " componentInstance" + comp + " = component" + comp + ".read(field" + comp + ", (long) (isSelf" + comp + " ? i : 0) * size" + comp + ")");
            }
        }
    }

    private void emitCallbackAccept(CodeBuilder body, int level, int n, ViewMode vm, EntityMode em) {
        String args = buildArgs(vm == ViewMode.COMPONENT_VIEW ? "componentView" : "componentInstance", n);
        if (em == EntityMode.WITH_ENTITY) {
            appendStatement(body, level, "callback.accept(entityId, " + args + ")");
        } else if (em == EntityMode.WITH_ITER) {
            appendStatement(body, level, "callback.accept(iter, i, " + args + ")");
        } else {
            appendStatement(body, level, "callback.accept(" + args + ")");
        }
    }
}