package io.github.elebras1.flecs;

import io.github.elebras1.flecs.internal.codegen.CodeBuilder;
import io.github.elebras1.flecs.internal.codegen.SourceFile;

import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.ArrayList;
import java.util.List;

public class WorldBaseGenerator extends AbstractBaseGenerator {

    private static final String QUERY_FQN = "io.github.elebras1.flecs.Query";

    public static void main(String[] args) {
        Path outputDir = args.length > 0 ? Paths.get(args[0]) : Paths.get("src/main/generated");
        WorldBaseGenerator generator = new WorldBaseGenerator();
        int count = generator.generateAndWrite(outputDir);
        System.out.println("Generated " + count + " files in " + outputDir.toAbsolutePath());
    }

    @Override
    public List<SourceFile> generate() {
        List<SourceFile> files = new ArrayList<>();
        files.add(generateWorldBase());
        return files;
    }

    private SourceFile generateWorldBase() {
        CodeBuilder body = new CodeBuilder();

        body.append("public abstract class WorldBase {").newline();
        body.newline();
        appendLine(body, 1, "protected abstract " + simpleName(QUERY_FQN) + " query(Class<?>... componentClasses);");

        for (int n = 1; n <= MAX_COMPONENTS; n++) {
            for (ViewMode vm : ViewMode.values()) {
                for (EntityMode em : EntityMode.values()) {
                    body.newline();
                    appendWorldEachMethod(body, n, vm, em);
                }
            }
        }

        body.append("}").newline();

        return SourceFile.builder(GENERATED_PACKAGE, "WorldBase")
                .fileComment("Generated by WorldBaseGenerator.")
                .classBody(body.toString())
                .build();
    }

    private void appendWorldEachMethod(CodeBuilder body, int n, ViewMode vm, EntityMode em) {
        List<String> compVars = compTypeVars(n);
        List<String> viewVars = viewTypeVars(n);
        List<String> typeDecls = new ArrayList<>(compVars);
        if (vm == ViewMode.COMPONENT_VIEW) {
            for (String v : viewVars) {
                typeDecls.add(v + " extends " + simpleName(COMPONENT_VIEW_FQN));
            }
        }

        String methodName = vm == ViewMode.COMPONENT_VIEW ? "eachView" : "each";

        StringBuilder signature = new StringBuilder();
        signature.append("public ");
        if (!typeDecls.isEmpty()) {
            signature.append("<").append(join(typeDecls)).append("> ");
        }
        signature.append("void ").append(methodName).append("(");

        List<String> params = new ArrayList<>();
        List<String> compArgs = new ArrayList<>();
        for (String compVar : compVars) {
            params.add("Class<" + compVar + "> componentClass" + compVar);
            compArgs.add("componentClass" + compVar);
        }

        String callbackType = callbackInterfaceName(n, vm, em) + "<"
                + join(vm == ViewMode.COMPONENT_VIEW ? viewVars : compVars) + ">";
        params.add(callbackType + " callback");

        signature.append(join(params)).append(") {");
        appendLine(body, 1, signature.toString());
        appendStatement(body, 2, simpleName(QUERY_FQN) + " query = this.query(" + join(compArgs) + ")");
        appendLine(body, 2, "try {");
        appendStatement(body, 3, "query." + methodName + "(" + join(compArgs) + ", callback)");
        appendLine(body, 2, "} finally {");
        appendStatement(body, 3, "query.destroy()");
        appendLine(body, 2, "}");
        appendLine(body, 1, "}");
    }
}
