package com.github.elebras1.flecs;

public record FlecsInfo(long lastComponentId,
                        long minId,
                        long maxId,
                        float deltaTimeRaw,
                        float deltaTime,
                        float timeScale,
                        float targetFps,
                        float frameTimeTotal,
                        float systemTimeTotal,
                        float emitTimeTotal,
                        float mergeTimeTotal,
                        float rematchTimeTotal,
                        double worldTimeTotal,
                        double worldTimeTotalRaw,
                        long frameCountTotal,
                        long mergeCountTotal,
                        long evalCompMonitorsTotal,
                        long rematchCountTotal,
                        long idCreateTotal,
                        long idDeleteTotal,
                        long tableCreateTotal,
                        long tableDeleteTotal,
                        long pipelineBuildCountTotal,
                        long systemsRanTotal,
                        long observersRanTotal,
                        long queriesRanTotal,
                        int tagIdCount,
                        int componentIdCount,
                        int pairIdCount,
                        int tableCount,
                        int creationTime,
                        CommandStats cmd,
                        String namePrefix) {
    public record CommandStats(
            long addCount,
            long removeCount,
            long deleteCount,
            long clearCount,
            long setCount,
            long ensureCount,
            long modifiedCount,
            long discardCount,
            long eventCount,
            long otherCount,
            long batchedEntityCount,
            long batchedCommandCount
    ) {}
}
