package io.github.elebras1.flecs.processor;

import io.github.elebras1.flecs.internal.codegen.CodeBuilder;
import io.github.elebras1.flecs.internal.codegen.SourceFile;

import javax.lang.model.element.TypeElement;
import javax.lang.model.element.VariableElement;
import javax.lang.model.type.ArrayType;
import javax.lang.model.type.TypeMirror;
import java.util.List;

public class ComponentViewGenerator extends AbstractGenerator {

    private static final String COMPONENT_VIEW_INTERFACE = "io.github.elebras1.flecs.ComponentView";
    private static final String MEMORY_ACCESS_CLASS = "io.github.elebras1.flecs.internal.MemoryAccess";
    private static final String WORLD_CLASS = "io.github.elebras1.flecs.World";

    @Override
    public SourceFile generate(TypeElement recordElement, List<VariableElement> fields) {
        String packageName = this.getPackageName(recordElement);
        String recordName = recordElement.getSimpleName().toString();
        String componentViewClassName = recordName + "View";
        String componentReference = packageName + "." + recordName + "Component";

        CodeBuilder body = new CodeBuilder();
        body.append("public class ").append(componentViewClassName).append(" implements ComponentView {").newline();

        body.indent4().append("protected long baseAddress;").newline();

        body.newline();
        body.indent4().append("/**").newline();
        body.indent4().append(" * Internal API - Do not use.").newline();
        body.indent4().append(" */").newline();
        body.indent4().append("@Override").newline();
        body.indent4().append("public void setBaseAddress(long baseAddress) {").newline();
        body.indent8().append("this.baseAddress = baseAddress;").newline();
        body.indent4().append("}").newline();

        for (VariableElement field : fields) {
            body.append(buildFieldMethods(field, componentReference));
        }

        body.append("}").newline();

        return SourceFile.builder(packageName, componentViewClassName)
                .fileComment("Generated by ComponentViewGenerator")
                .addImport(COMPONENT_VIEW_INTERFACE)
                .addImport(MEMORY_ACCESS_CLASS)
                .addImport(WORLD_CLASS)
                .classBody(body.toString())
                .build();
    }

    private String buildFieldMethods(VariableElement field, String componentReference) {
        String fieldName = field.getSimpleName().toString();
        String offsetName = "OFFSET_" + fieldName.toUpperCase();
        String typeName = field.asType().toString();
        CodeBuilder sb = new CodeBuilder();

        if (typeName.endsWith("[]")) {
            int length = this.getArrayLength(field);
            String elementType = this.getElementTypeName(field);
            String suffix = Character.toUpperCase(elementType.charAt(0)) + elementType.substring(1);
            String methodAtIndex = "get" + suffix + "AtIndex";

            sb.newline();
            sb.indent4().append("public int ").append(fieldName).append("Length() {").newline();
            sb.indent8().append("return ").append(length).append(";").newline();
            sb.indent4().append("}").newline();

            sb.newline();
            sb.indent4().append("public ").append(elementType).append(" ").append(fieldName).append("(int index) {").newline();
            sb.indent8().append("assert baseAddress != 0 : \"View is not bound to a component\";").newline();
            sb.indent8().append("return MemoryAccess.").append(methodAtIndex)
                    .append("(World.WHOLE_MEMORY, baseAddress + ").append(componentReference).append(".").append(offsetName).append(", index);").newline();
            sb.indent4().append("}").newline();
        } else {
            String getter = this.getGetterMethod(typeName);
            String javaType = "java.lang.String".equals(typeName) ? "String" : typeName;

            sb.newline();
            sb.indent4().append("public ").append(javaType).append(" ").append(fieldName).append("() {").newline();
            sb.indent8().append("assert baseAddress != 0 : \"View is not bound to a component\";").newline();
            if ("java.lang.String".equals(typeName)) {
                int size = this.getStringSize(field);
                sb.indent8().append("return MemoryAccess.").append(getter)
                        .append("(World.WHOLE_MEMORY, baseAddress + ").append(componentReference).append(".").append(offsetName)
                        .append(", ").append(size).append(");").newline();
            } else {
                sb.indent8().append("return MemoryAccess.").append(getter)
                        .append("(World.WHOLE_MEMORY, baseAddress + ").append(componentReference).append(".").append(offsetName).append(");").newline();
            }
            sb.indent4().append("}").newline();
        }

        return sb.toString();
    }

    private String getElementTypeName(VariableElement field) {
        TypeMirror typeMirror = field.asType();
        if (typeMirror instanceof ArrayType arrayType) {
            return arrayType.getComponentType().toString();
        }
        return typeMirror.toString();
    }
}
