package io.github.elebras1.flecs.processor;

import io.github.elebras1.flecs.internal.codegen.CodeBuilder;
import io.github.elebras1.flecs.internal.codegen.SourceFile;

import javax.lang.model.element.TypeElement;
import javax.lang.model.element.VariableElement;
import javax.lang.model.type.ArrayType;
import javax.lang.model.type.TypeMirror;
import java.util.List;

public class ComponentMutViewGenerator extends AbstractGenerator {

    private static final String COMPONENT_MUT_VIEW_INTERFACE = "io.github.elebras1.flecs.ComponentMutView";
    private static final String MEMORY_ACCESS_CLASS = "io.github.elebras1.flecs.internal.MemoryAccess";
    private static final String WORLD_CLASS = "io.github.elebras1.flecs.World";

    @Override
    public SourceFile generate(TypeElement recordElement, List<VariableElement> fields) {
        String packageName = this.getPackageName(recordElement);
        String recordName = recordElement.getSimpleName().toString();
        String componentMutViewClassName = recordName + "MutView";
        String baseViewClassName = recordName + "View";
        String componentReference = packageName + "." + recordName + "Component";

        CodeBuilder body = new CodeBuilder();
        body.append("public final class ").append(componentMutViewClassName)
                .append(" extends ").append(baseViewClassName)
                .append(" implements ComponentMutView {").newline();

        for (VariableElement field : fields) {
            body.append(buildFieldMethods(field, componentReference, componentMutViewClassName));
        }

        body.append("}").newline();

        return SourceFile.builder(packageName, componentMutViewClassName)
                .fileComment("Generated by ComponentMutViewGenerator")
                .addImport(COMPONENT_MUT_VIEW_INTERFACE)
                .addImport(MEMORY_ACCESS_CLASS)
                .addImport(WORLD_CLASS)
                .classBody(body.toString())
                .build();
    }

    private String buildFieldMethods(VariableElement field, String componentReference, String viewType) {
        String fieldName = field.getSimpleName().toString();
        String offsetName = "OFFSET_" + fieldName.toUpperCase();
        String typeName = field.asType().toString();
        CodeBuilder sb = new CodeBuilder();

        if (typeName.endsWith("[]")) {
            String elementType = this.getElementTypeName(field);
            String suffix = Character.toUpperCase(elementType.charAt(0)) + elementType.substring(1);
            String setterAtIndex = "set" + suffix + "AtIndex";

            sb.newline();
            sb.indent4().append("public ").append(viewType).append(" ").append(fieldName).append("(int index, ").append(elementType).append(" value) {").newline();
            sb.indent8().append("assert baseAddress != 0 : \"View is not bound to a component\";").newline();
            sb.indent8().append("MemoryAccess.").append(setterAtIndex)
                    .append("(World.WHOLE_MEMORY, baseAddress + ").append(componentReference).append(".").append(offsetName).append(", index, value);").newline();
            sb.indent8().append("return this;").newline();
            sb.indent4().append("}").newline();
        } else {
            String javaType = "java.lang.String".equals(typeName) ? "String" : typeName;

            sb.newline();
            sb.indent4().append("public ").append(viewType).append(" ").append(fieldName).append("(").append(javaType).append(" value) {").newline();
            sb.indent8().append("assert baseAddress != 0 : \"View is not bound to a component\";").newline();
            if ("java.lang.String".equals(typeName)) {
                int size = this.getStringSize(field);
                sb.indent8().append("MemoryAccess.set(World.WHOLE_MEMORY, baseAddress + ").append(componentReference).append(".").append(offsetName)
                        .append(", value, ").append(size).append(");").newline();
            } else {
                sb.indent8().append("MemoryAccess.set(World.WHOLE_MEMORY, baseAddress + ").append(componentReference).append(".").append(offsetName).append(", value);").newline();
            }
            sb.indent8().append("return this;").newline();
            sb.indent4().append("}").newline();
        }

        return sb.toString();
    }

    private String getElementTypeName(VariableElement field) {
        TypeMirror typeMirror = field.asType();
        if (typeMirror instanceof ArrayType arrayType) {
            return arrayType.getComponentType().toString();
        }
        return typeMirror.toString();
    }
}
